name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Install dependencies
      - run: npm ci

      # Build the React app
      - run: npm run build

      # Run tests with coverage (Vitest)
      - run: npm run test:coverage
        env:
          CI: true # Ensures Vitest runs in CI mode

      # Extract and display coverage
      - run: |
          COVERAGE=$(node -e "const report = require('./coverage/coverage-summary.json'); console.log(report.total.statements.pct);")
          echo "Test Coverage: $COVERAGE%"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Install dependencies
      - run: npm ci

      # Build the app
      - run: npm run build

      # Deploy to Netlify
      - run: npm install -g netlify-cli && netlify deploy --prod --dir=build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}