name: Test Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./Lance-Sports
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
        echo "Ensuring coverage provider is installed..."
        npm install --save-dev @vitest/coverage-v8

    - name: Run Vitest with coverage
      working-directory: ./Lance-Sports
      run: |
        echo "Running test suite with coverage..."
        npm run test:coverage

    - name: Verify coverage output
      working-directory: ./Lance-Sports
      run: |
        if [ -f "coverage/lcov.info" ]; then
          echo "✅ Found coverage/lcov.info"
        else
          echo "❌ coverage/lcov.info not found!"
          ls -la coverage || echo "No coverage directory found"
          exit 1
        fi

    - name: Upload coverage to Coveralls
      if: always()
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./Lance-Sports/coverage/lcov.info
        # For private repos, uncomment and add a secret:
        # token: ${{ secrets.COVERALLS_REPO_TOKEN }}
